name: Build Mod and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build mod jar
        run: ./gradlew deploy
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            This is an automated release for version ${{ github.run_number }}.
      - name: Upload built jar file
        uses: actions/upload-artifact@v2
        with:
          name: Built Jar
          path: build/libs/${{ github.event.repository.name }}.jar
